### ISSUE TITLE
CJS build

### ISSUE THREAD

**Issue by flaviouk** [emilkowalski/sonner#17]
Great job on this package, it works perfectly and uses the same API as https://github.com/timolins/react-hot-toast :)

I did have a few problems when integrating it:
- Importing in a remix app doesn't work (I can get around it by forcing remix to build the lib on the server - as you only provide ESM output)
- Related to the previous point, when doing this styles are not injected nor are they provided as part of the published step, so I had to copy them in my code base, ideally we should be able to do `@import 'sonner/styles.css'` or something similar

**Comment by emilkowalski** [comment]
This has been fixed in the newest relelase!

**Comment by VityaSchel** [comment]
How to use it with remix? I still don't get it, it must export some kind of CSS stylesheet

**Comment by TristanBlackwell** [comment]
I've had this working without anything special styling wise. You can add the `<Toaster />` component next to your `<Outlet />` in _root.tsx_ and should be good to go.

```
<body>
        <Toaster richColors visibleToasts={1} />
        <Outlet />
        <ScrollRestoration />
        <LiveReload />
        <Scripts />
</body>
```

**Comment by VityaSchel** [comment]
> I've had this working without anything special styling wise. You can add the `<Toaster />` component next to your `<Outlet />` in _root.tsx_ and should be good to go.
> 
> ```
> <body>
>         <Toaster richColors visibleToasts={1} />
>         <Outlet />
>         <ScrollRestoration />
>         <LiveReload />
>         <Scripts />
> </body>
> ```

In my case it renders toast but without styles

**Comment by TristanBlackwell** [comment]
Can you provide a reproducible example? 

I've just spun up a create-remix-app (V2.5.1) and installed sonner (V1.3.1) and it is styled as expected

**Comment by VityaSchel** [comment]
> Can you provide a reproducible example? 
> 
> I've just spun up a create-remix-app (V2.5.1) and installed sonner (V1.3.1) and it is styled as expected

I think it may be related to remix-i18next because it sets custom server and client? I'm not sure because I'm working with remix for first time
Here is my project: https://github.com/VityaSchel/session-bots-directory
Start project, go to root.tsx, remove copied from sonner stylesheet import

**Comment by TristanBlackwell** [comment]
I believe your correct. This needs some more digging yet but the styles are not being injected automatically on the client.

I can see some hydration errors in the console once the toaster component is introduced so I'd say this is the place to start... 🧐
